# Generated by Django 3.2.4 on 2021-06-04 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('gender', models.SmallIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('session', models.IntegerField(default=0)),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('progress', models.CharField(default=0, max_length=100)),
                ('selection_menu', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm_from', models.IntegerField(default=0)),
                ('menu_id', models.IntegerField(default=0)),
                ('menu_item_id', models.IntegerField(default=0)),
                ('access_count', models.IntegerField(default=0)),
                ('is_registration_done', models.IntegerField(default=0)),
                ('short_code', models.CharField(default=0, max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'Users Data',
            },
        ),
        migrations.CreateModel(
            name='UssdLog',
            fields=[
                ('session_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'Users Logs',
            },
        ),
    ]
